version: "3"
services:
  centos:
    # 適宜変えること
    container_name: "ryuou-ssh"
    image: centos
    tty: true
    # 適宜変えること
    ports:
      - "127.0.0.1:22222:22"
    privileged: true
    command: /sbin/init
    # 適宜変えること
    volumes:
      - "./centos/etc/ssh:/etc/ssh"
    #   - "./centos/root:/root"
    #   - "./centos/var:/var"
