version: '3.1'
services:
  centos:
    image: centos
    container_name: "dns-server"
    tty: true
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    privileged: true
    command: /sbin/init
    cap_add:
      - NET_ADMIN